//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.08 at 07:27:40 PM CEST 
//


package it.gov.agid.protocollo;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AmministrazioneType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AmministrazioneType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="DenominazioneAmministrazione" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="CFAmministrazione" type="{http://www.agid.gov.it/protocollo/}PartitaIVA" minOccurs="0"/&gt;
 *         &lt;element name="CodiceIPAAmministrazione" type="{http://www.agid.gov.it/protocollo/}CodiceIPA"/&gt;
 *         &lt;element name="ContattiAmministrazione" type="{http://www.agid.gov.it/protocollo/}ContattiType" minOccurs="0"/&gt;
 *         &lt;element name="CodiceIPAAOO" type="{http://www.agid.gov.it/protocollo/}CodiceIPA" minOccurs="0"/&gt;
 *         &lt;element name="ContattiAOO" type="{http://www.agid.gov.it/protocollo/}ContattiType" minOccurs="0"/&gt;
 *         &lt;element name="CodiceIPAUO" type="{http://www.agid.gov.it/protocollo/}CodiceIPA" minOccurs="0"/&gt;
 *         &lt;element name="ContattiUO" type="{http://www.agid.gov.it/protocollo/}ContattiType" minOccurs="0"/&gt;
 *         &lt;element name="PersonaFisica" type="{http://www.agid.gov.it/protocollo/}PersonaFisicaType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AmministrazioneType", propOrder = {
    "denominazioneAmministrazione",
    "cfAmministrazione",
    "codiceIPAAmministrazione",
    "contattiAmministrazione",
    "codiceIPAAOO",
    "contattiAOO",
    "codiceIPAUO",
    "contattiUO",
    "personaFisica"
})
public class AmministrazioneType {

    @XmlElement(name = "DenominazioneAmministrazione", required = true)
    protected String denominazioneAmministrazione;
    @XmlElement(name = "CFAmministrazione")
    protected String cfAmministrazione;
    @XmlElement(name = "CodiceIPAAmministrazione", required = true)
    protected CodiceIPA codiceIPAAmministrazione;
    @XmlElement(name = "ContattiAmministrazione")
    protected ContattiType contattiAmministrazione;
    @XmlElement(name = "CodiceIPAAOO")
    protected CodiceIPA codiceIPAAOO;
    @XmlElement(name = "ContattiAOO")
    protected ContattiType contattiAOO;
    @XmlElement(name = "CodiceIPAUO")
    protected CodiceIPA codiceIPAUO;
    @XmlElement(name = "ContattiUO")
    protected ContattiType contattiUO;
    @XmlElement(name = "PersonaFisica")
    protected List<PersonaFisicaType> personaFisica;

    /**
     * Gets the value of the denominazioneAmministrazione property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDenominazioneAmministrazione() {
        return denominazioneAmministrazione;
    }

    /**
     * Sets the value of the denominazioneAmministrazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDenominazioneAmministrazione(String value) {
        this.denominazioneAmministrazione = value;
    }

    /**
     * Gets the value of the cfAmministrazione property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCFAmministrazione() {
        return cfAmministrazione;
    }

    /**
     * Sets the value of the cfAmministrazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCFAmministrazione(String value) {
        this.cfAmministrazione = value;
    }

    /**
     * Gets the value of the codiceIPAAmministrazione property.
     * 
     * @return
     *     possible object is
     *     {@link CodiceIPA }
     *     
     */
    public CodiceIPA getCodiceIPAAmministrazione() {
        return codiceIPAAmministrazione;
    }

    /**
     * Sets the value of the codiceIPAAmministrazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodiceIPA }
     *     
     */
    public void setCodiceIPAAmministrazione(CodiceIPA value) {
        this.codiceIPAAmministrazione = value;
    }

    /**
     * Gets the value of the contattiAmministrazione property.
     * 
     * @return
     *     possible object is
     *     {@link ContattiType }
     *     
     */
    public ContattiType getContattiAmministrazione() {
        return contattiAmministrazione;
    }

    /**
     * Sets the value of the contattiAmministrazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContattiType }
     *     
     */
    public void setContattiAmministrazione(ContattiType value) {
        this.contattiAmministrazione = value;
    }

    /**
     * Gets the value of the codiceIPAAOO property.
     * 
     * @return
     *     possible object is
     *     {@link CodiceIPA }
     *     
     */
    public CodiceIPA getCodiceIPAAOO() {
        return codiceIPAAOO;
    }

    /**
     * Sets the value of the codiceIPAAOO property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodiceIPA }
     *     
     */
    public void setCodiceIPAAOO(CodiceIPA value) {
        this.codiceIPAAOO = value;
    }

    /**
     * Gets the value of the contattiAOO property.
     * 
     * @return
     *     possible object is
     *     {@link ContattiType }
     *     
     */
    public ContattiType getContattiAOO() {
        return contattiAOO;
    }

    /**
     * Sets the value of the contattiAOO property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContattiType }
     *     
     */
    public void setContattiAOO(ContattiType value) {
        this.contattiAOO = value;
    }

    /**
     * Gets the value of the codiceIPAUO property.
     * 
     * @return
     *     possible object is
     *     {@link CodiceIPA }
     *     
     */
    public CodiceIPA getCodiceIPAUO() {
        return codiceIPAUO;
    }

    /**
     * Sets the value of the codiceIPAUO property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodiceIPA }
     *     
     */
    public void setCodiceIPAUO(CodiceIPA value) {
        this.codiceIPAUO = value;
    }

    /**
     * Gets the value of the contattiUO property.
     * 
     * @return
     *     possible object is
     *     {@link ContattiType }
     *     
     */
    public ContattiType getContattiUO() {
        return contattiUO;
    }

    /**
     * Sets the value of the contattiUO property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContattiType }
     *     
     */
    public void setContattiUO(ContattiType value) {
        this.contattiUO = value;
    }

    /**
     * Gets the value of the personaFisica property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the personaFisica property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPersonaFisica().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PersonaFisicaType }
     * 
     * 
     */
    public List<PersonaFisicaType> getPersonaFisica() {
        if (personaFisica == null) {
            personaFisica = new ArrayList<PersonaFisicaType>();
        }
        return this.personaFisica;
    }

}
