//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.08 at 07:27:40 PM CEST 
//


package it.gov.agid.protocollo;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AmministrazioneEsteraType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AmministrazioneEsteraType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="DenominazioneAmministrazione" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="DenominazioneUfficio" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ContattiAmministrazione" type="{http://www.agid.gov.it/protocollo/}ContattiType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AmministrazioneEsteraType", propOrder = {
    "denominazioneAmministrazione",
    "denominazioneUfficio",
    "contattiAmministrazione"
})
public class AmministrazioneEsteraType {

    @XmlElement(name = "DenominazioneAmministrazione", required = true)
    protected String denominazioneAmministrazione;
    @XmlElement(name = "DenominazioneUfficio")
    protected String denominazioneUfficio;
    @XmlElement(name = "ContattiAmministrazione")
    protected ContattiType contattiAmministrazione;

    /**
     * Gets the value of the denominazioneAmministrazione property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDenominazioneAmministrazione() {
        return denominazioneAmministrazione;
    }

    /**
     * Sets the value of the denominazioneAmministrazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDenominazioneAmministrazione(String value) {
        this.denominazioneAmministrazione = value;
    }

    /**
     * Gets the value of the denominazioneUfficio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDenominazioneUfficio() {
        return denominazioneUfficio;
    }

    /**
     * Sets the value of the denominazioneUfficio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDenominazioneUfficio(String value) {
        this.denominazioneUfficio = value;
    }

    /**
     * Gets the value of the contattiAmministrazione property.
     * 
     * @return
     *     possible object is
     *     {@link ContattiType }
     *     
     */
    public ContattiType getContattiAmministrazione() {
        return contattiAmministrazione;
    }

    /**
     * Sets the value of the contattiAmministrazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContattiType }
     *     
     */
    public void setContattiAmministrazione(ContattiType value) {
        this.contattiAmministrazione = value;
    }

}
