//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.08 at 07:27:40 PM CEST 
//


package it.gov.agid.protocollo;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 * 				La classificazione riporta il valore attribuito al messaggio di protocollo.
 * 				
 * 				La classificazione è caratterizzata da:
 * 				- Denominazione, una desccrizione della classificazione attribuita
 * 				- In alternativa il codice di classificazione può essere rappresentato:
 * 					- CodiceFlat, l'unione in un'unico element di categoria, classe ed eventuale sottoclasse 
 * 						es. 
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodiceFlat xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:prot="http://www.agid.gov.it/protocollo/" xmlns:xs="http://www.w3.org/2001/XMLSchema"&gt;Titolo I.Classe 1&lt;/CodiceFlat&gt;
 * </pre>
 * 
 * 					- CodicePath, la separazione in differenti element di categoria, classe ed eventuale sottoclasse 
 * 						es. 
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;CodicePath xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:prot="http://www.agid.gov.it/protocollo/" xmlns:xs="http://www.w3.org/2001/XMLSchema"&gt;&lt;Livello&gt;Titolo I&lt;/Livello&gt;&lt;SubLivello&gt;&lt;Livello&gt;Classe 1&lt;/Livello&gt;&#13;
 * 								&lt;/SubLivello&gt;&#13;
 * 							&lt;/CodicePath&gt;
 * </pre>
 * 
 * 			
 * 
 * <p>Java class for ClassificaType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ClassificaType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Denominazione" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;choice&gt;
 *           &lt;element name="CodiceFlat" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *           &lt;element name="CodicePath" type="{http://www.agid.gov.it/protocollo/}LivelloType"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ClassificaType", propOrder = {
    "denominazione",
    "codiceFlat",
    "codicePath"
})
public class ClassificaType {

    @XmlElement(name = "Denominazione", required = true)
    protected String denominazione;
    @XmlElement(name = "CodiceFlat")
    protected String codiceFlat;
    @XmlElement(name = "CodicePath")
    protected LivelloType codicePath;

    /**
     * Gets the value of the denominazione property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDenominazione() {
        return denominazione;
    }

    /**
     * Sets the value of the denominazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDenominazione(String value) {
        this.denominazione = value;
    }

    /**
     * Gets the value of the codiceFlat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodiceFlat() {
        return codiceFlat;
    }

    /**
     * Sets the value of the codiceFlat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodiceFlat(String value) {
        this.codiceFlat = value;
    }

    /**
     * Gets the value of the codicePath property.
     * 
     * @return
     *     possible object is
     *     {@link LivelloType }
     *     
     */
    public LivelloType getCodicePath() {
        return codicePath;
    }

    /**
     * Sets the value of the codicePath property.
     * 
     * @param value
     *     allowed object is
     *     {@link LivelloType }
     *     
     */
    public void setCodicePath(LivelloType value) {
        this.codicePath = value;
    }

}
