//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.08 at 07:27:40 PM CEST 
//


package it.gov.agid.protocollo;

import java.math.BigInteger;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 * 				Specifica un riferimento telematico per recuperare la risorsa.
 * 				
 * 				Il recupero della risorsa avviene tramite HTTP GET con autenticazione conforme all’RFC 7617 su canale di trasporto TLS.
 * 				
 * 					Esempio di chiamata:
 * 						GET /PathValue HTTP/1.1
 * 						Host: HostValue
 * 						Authorization: Basic basic-credentials
 * 						
 * 						
 * 				- HostValue, server che espone la risorsa
 * 				- PathValue, riferimento alla risorsa da recuperare
 * 				- timeToLive, numero di millisecondi di disponibilità della risorsa
 * 				- userId, user-id comunicata dall’AOO Mittente													
 * 				- password, password comunicata dall’AOO Mittente
 * 			
 * 
 * <p>Java class for CollocazioneTelematicaType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CollocazioneTelematicaType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="HostValue" type="{http://www.w3.org/2001/XMLSchema}anyURI"/&gt;
 *         &lt;element name="PathValue" type="{http://www.w3.org/2001/XMLSchema}anyURI"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="timeToLive" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="userId" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="password" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CollocazioneTelematicaType", propOrder = {
    "hostValue",
    "pathValue"
})
public class CollocazioneTelematicaType {

    @XmlElement(name = "HostValue", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String hostValue;
    @XmlElement(name = "PathValue", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String pathValue;
    @XmlAttribute(name = "timeToLive", namespace = "http://www.agid.gov.it/protocollo/")
    protected BigInteger timeToLive;
    @XmlAttribute(name = "userId", namespace = "http://www.agid.gov.it/protocollo/")
    protected String userId;
    @XmlAttribute(name = "password", namespace = "http://www.agid.gov.it/protocollo/")
    protected String password;

    /**
     * Gets the value of the hostValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHostValue() {
        return hostValue;
    }

    /**
     * Sets the value of the hostValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHostValue(String value) {
        this.hostValue = value;
    }

    /**
     * Gets the value of the pathValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPathValue() {
        return pathValue;
    }

    /**
     * Sets the value of the pathValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPathValue(String value) {
        this.pathValue = value;
    }

    /**
     * Gets the value of the timeToLive property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTimeToLive() {
        return timeToLive;
    }

    /**
     * Sets the value of the timeToLive property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTimeToLive(BigInteger value) {
        this.timeToLive = value;
    }

    /**
     * Gets the value of the userId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserId() {
        return userId;
    }

    /**
     * Sets the value of the userId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserId(String value) {
        this.userId = value;
    }

    /**
     * Gets the value of the password property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the value of the password property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassword(String value) {
        this.password = value;
    }

}
