//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.08 at 07:27:40 PM CEST 
//


package it.gov.agid.protocollo;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 * 				L'insieme di contatti, e nel dettaglio:
 * 				- IndirizzoPostale, un'indirizzo relativo
 * 				- IndirizzoTelematico, un'indirizzo elettronico
 * 				- Telefono, un conctatto telefonico
 * 			
 * 
 * <p>Java class for ContattiType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ContattiType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="IndirizzoPostale" type="{http://www.agid.gov.it/protocollo/}IndirizzoPostaleType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="IndirizzoTelematico" type="{http://www.agid.gov.it/protocollo/}IndirizzoTelematicoType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Telefono" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ContattiType", propOrder = {
    "indirizzoPostale",
    "indirizzoTelematico",
    "telefono"
})
public class ContattiType {

    @XmlElement(name = "IndirizzoPostale")
    protected List<IndirizzoPostaleType> indirizzoPostale;
    @XmlElement(name = "IndirizzoTelematico")
    protected List<IndirizzoTelematicoType> indirizzoTelematico;
    @XmlElement(name = "Telefono")
    protected List<String> telefono;

    /**
     * Gets the value of the indirizzoPostale property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the indirizzoPostale property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIndirizzoPostale().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IndirizzoPostaleType }
     * 
     * 
     */
    public List<IndirizzoPostaleType> getIndirizzoPostale() {
        if (indirizzoPostale == null) {
            indirizzoPostale = new ArrayList<IndirizzoPostaleType>();
        }
        return this.indirizzoPostale;
    }

    /**
     * Gets the value of the indirizzoTelematico property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the indirizzoTelematico property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIndirizzoTelematico().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IndirizzoTelematicoType }
     * 
     * 
     */
    public List<IndirizzoTelematicoType> getIndirizzoTelematico() {
        if (indirizzoTelematico == null) {
            indirizzoTelematico = new ArrayList<IndirizzoTelematicoType>();
        }
        return this.indirizzoTelematico;
    }

    /**
     * Gets the value of the telefono property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the telefono property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTelefono().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getTelefono() {
        if (telefono == null) {
            telefono = new ArrayList<String>();
        }
        return this.telefono;
    }

}
