//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.08 at 07:27:40 PM CEST 
//


package it.gov.agid.protocollo;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 * 				La descrizione contiene i dati descrittivi del messaggio di protocollato.
 * 				
 * 				La descrizione è caratterizzata da:
 * 				- Mittente, riferimento del mittente (organizzazione o persona)
 * 				- Destinatario, riferimento del destinatario (organizzazione o persona) 
 * 				- DocumentoPrimario, riferimento al documento primario del messaggio di protocollo
 * 				- Allegato, riferimento ad uno degli allegati del messaggio di protocollo se presente
 * 			
 * 
 * <p>Java class for DescrizioneType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DescrizioneType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Mittente" type="{http://www.agid.gov.it/protocollo/}SoggettoType"/&gt;
 *         &lt;element name="Destinatario" type="{http://www.agid.gov.it/protocollo/}DestinatarioType" maxOccurs="unbounded"/&gt;
 *         &lt;element name="DocumentoPrimario" type="{http://www.agid.gov.it/protocollo/}DocumentoType"/&gt;
 *         &lt;element name="Allegato" type="{http://www.agid.gov.it/protocollo/}DocumentoType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DescrizioneType", propOrder = {
    "mittente",
    "destinatario",
    "documentoPrimario",
    "allegato"
})
public class DescrizioneType {

    @XmlElement(name = "Mittente", required = true)
    protected SoggettoType mittente;
    @XmlElement(name = "Destinatario", required = true)
    protected List<DestinatarioType> destinatario;
    @XmlElement(name = "DocumentoPrimario", required = true)
    protected DocumentoType documentoPrimario;
    @XmlElement(name = "Allegato")
    protected List<DocumentoType> allegato;

    /**
     * Gets the value of the mittente property.
     * 
     * @return
     *     possible object is
     *     {@link SoggettoType }
     *     
     */
    public SoggettoType getMittente() {
        return mittente;
    }

    /**
     * Sets the value of the mittente property.
     * 
     * @param value
     *     allowed object is
     *     {@link SoggettoType }
     *     
     */
    public void setMittente(SoggettoType value) {
        this.mittente = value;
    }

    /**
     * Gets the value of the destinatario property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the destinatario property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDestinatario().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DestinatarioType }
     * 
     * 
     */
    public List<DestinatarioType> getDestinatario() {
        if (destinatario == null) {
            destinatario = new ArrayList<DestinatarioType>();
        }
        return this.destinatario;
    }

    /**
     * Gets the value of the documentoPrimario property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentoType }
     *     
     */
    public DocumentoType getDocumentoPrimario() {
        return documentoPrimario;
    }

    /**
     * Sets the value of the documentoPrimario property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentoType }
     *     
     */
    public void setDocumentoPrimario(DocumentoType value) {
        this.documentoPrimario = value;
    }

    /**
     * Gets the value of the allegato property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the allegato property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAllegato().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DocumentoType }
     * 
     * 
     */
    public List<DocumentoType> getAllegato() {
        if (allegato == null) {
            allegato = new ArrayList<DocumentoType>();
        }
        return this.allegato;
    }

}
