//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.08 at 07:27:40 PM CEST 
//


package it.gov.agid.protocollo;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 * 				Estende il data type SoggettoType con gli attributi:
 * 				- confermaRicezione, per permettere al mittende di indicare che richiede la conferma di ricezione del messaggio inoltrato
 * 				- perConoscenza, per permettere al mittende di indicare che il messaggio è stato inoltrato per conoscenza					
 * 			
 * 
 * <p>Java class for DestinatarioType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DestinatarioType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.agid.gov.it/protocollo/}SoggettoType"&gt;
 *       &lt;attribute name="confermaRicezione" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" /&gt;
 *       &lt;attribute name="perConoscenza" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DestinatarioType")
public class DestinatarioType
    extends SoggettoType
{

    @XmlAttribute(name = "confermaRicezione", namespace = "http://www.agid.gov.it/protocollo/")
    protected Boolean confermaRicezione;
    @XmlAttribute(name = "perConoscenza", namespace = "http://www.agid.gov.it/protocollo/")
    protected Boolean perConoscenza;

    /**
     * Gets the value of the confermaRicezione property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isConfermaRicezione() {
        if (confermaRicezione == null) {
            return true;
        } else {
            return confermaRicezione;
        }
    }

    /**
     * Sets the value of the confermaRicezione property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setConfermaRicezione(Boolean value) {
        this.confermaRicezione = value;
    }

    /**
     * Gets the value of the perConoscenza property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isPerConoscenza() {
        if (perConoscenza == null) {
            return false;
        } else {
            return perConoscenza;
        }
    }

    /**
     * Sets the value of the perConoscenza property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPerConoscenza(Boolean value) {
        this.perConoscenza = value;
    }

}
