//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.08 at 07:27:40 PM CEST 
//


package it.gov.agid.protocollo;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 * 				Il documento contiene i dati per referenziare un documento (documento primario o allegato) del messaggio di protocollo
 * 				
 * 				Il documento è caratterizzato da:
 * 				- Descrizione, la descrizione del contenuto dello specifico documento
 * 				- Impronta, l'impronta digitale (digest) del documento
 * 				- nomeFile, il nome del file relativo al documento
 * 				- mimeType, il mime type (RFC 6838) associto al documento
 * 				- firmatoDigitalmente, flag per indicare il documento è firmato digitalmente (sezione 4 Regolamento UE 910/2014) ed eventuale nome file detached e mime type (RFC 6838) associto allo stesso 				
 * 				- sigillatoElettronicamente, flag per indicare che al documento è apposto un sigillo elettronico (sezione 5 Regolamento UE 910/2014) ed eventuale nome file detached e mime type (RFC 6838) associto allo stesso
 * 				- marcaturaTemporale, flag per indicare che al documento è apposta una marca temporale (sezione 6 Regolamento UE 910/2014) ed eventuale nome file detached
 * 			
 * 
 * <p>Java class for DocumentoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DocumentoType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Descrizione" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Impronta" type="{http://www.agid.gov.it/protocollo/}ImprontaType"/&gt;
 *         &lt;element name="CollocazioneTelematica" type="{http://www.agid.gov.it/protocollo/}CollocazioneTelematicaType" minOccurs="0"/&gt;
 *         &lt;element name="firmatoDigitalmente" type="{http://www.agid.gov.it/protocollo/}SignType" minOccurs="0"/&gt;
 *         &lt;element name="sigillatoElettronicamente" type="{http://www.agid.gov.it/protocollo/}SignType" minOccurs="0"/&gt;
 *         &lt;element name="marcaturaTemporale" type="{http://www.agid.gov.it/protocollo/}SignType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="nomeFile" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="mimeType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DocumentoType", propOrder = {
    "descrizione",
    "impronta",
    "collocazioneTelematica",
    "firmatoDigitalmente",
    "sigillatoElettronicamente",
    "marcaturaTemporale"
})
public class DocumentoType {

    @XmlElement(name = "Descrizione")
    protected String descrizione;
    @XmlElement(name = "Impronta", required = true)
    protected ImprontaType impronta;
    @XmlElement(name = "CollocazioneTelematica")
    protected CollocazioneTelematicaType collocazioneTelematica;
    protected SignType firmatoDigitalmente;
    protected SignType sigillatoElettronicamente;
    protected SignType marcaturaTemporale;
    @XmlAttribute(name = "nomeFile", namespace = "http://www.agid.gov.it/protocollo/", required = true)
    protected String nomeFile;
    @XmlAttribute(name = "mimeType", namespace = "http://www.agid.gov.it/protocollo/", required = true)
    protected String mimeType;

    /**
     * Gets the value of the descrizione property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescrizione() {
        return descrizione;
    }

    /**
     * Sets the value of the descrizione property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescrizione(String value) {
        this.descrizione = value;
    }

    /**
     * Gets the value of the impronta property.
     * 
     * @return
     *     possible object is
     *     {@link ImprontaType }
     *     
     */
    public ImprontaType getImpronta() {
        return impronta;
    }

    /**
     * Sets the value of the impronta property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImprontaType }
     *     
     */
    public void setImpronta(ImprontaType value) {
        this.impronta = value;
    }

    /**
     * Gets the value of the collocazioneTelematica property.
     * 
     * @return
     *     possible object is
     *     {@link CollocazioneTelematicaType }
     *     
     */
    public CollocazioneTelematicaType getCollocazioneTelematica() {
        return collocazioneTelematica;
    }

    /**
     * Sets the value of the collocazioneTelematica property.
     * 
     * @param value
     *     allowed object is
     *     {@link CollocazioneTelematicaType }
     *     
     */
    public void setCollocazioneTelematica(CollocazioneTelematicaType value) {
        this.collocazioneTelematica = value;
    }

    /**
     * Gets the value of the firmatoDigitalmente property.
     * 
     * @return
     *     possible object is
     *     {@link SignType }
     *     
     */
    public SignType getFirmatoDigitalmente() {
        return firmatoDigitalmente;
    }

    /**
     * Sets the value of the firmatoDigitalmente property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignType }
     *     
     */
    public void setFirmatoDigitalmente(SignType value) {
        this.firmatoDigitalmente = value;
    }

    /**
     * Gets the value of the sigillatoElettronicamente property.
     * 
     * @return
     *     possible object is
     *     {@link SignType }
     *     
     */
    public SignType getSigillatoElettronicamente() {
        return sigillatoElettronicamente;
    }

    /**
     * Sets the value of the sigillatoElettronicamente property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignType }
     *     
     */
    public void setSigillatoElettronicamente(SignType value) {
        this.sigillatoElettronicamente = value;
    }

    /**
     * Gets the value of the marcaturaTemporale property.
     * 
     * @return
     *     possible object is
     *     {@link SignType }
     *     
     */
    public SignType getMarcaturaTemporale() {
        return marcaturaTemporale;
    }

    /**
     * Sets the value of the marcaturaTemporale property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignType }
     *     
     */
    public void setMarcaturaTemporale(SignType value) {
        this.marcaturaTemporale = value;
    }

    /**
     * Gets the value of the nomeFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNomeFile() {
        return nomeFile;
    }

    /**
     * Sets the value of the nomeFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNomeFile(String value) {
        this.nomeFile = value;
    }

    /**
     * Gets the value of the mimeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMimeType() {
        return mimeType;
    }

    /**
     * Sets the value of the mimeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMimeType(String value) {
        this.mimeType = value;
    }

}
