//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.08 at 07:27:40 PM CEST 
//


package it.gov.agid.protocollo;

import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 * 				Contiene i dati identificativi della segnatura di protocollo.
 * 				
 * 				L'indentificativo è caratterizzato da:
 * 					- CodiceAmministrazione, il codice IPA dell'amministrazione
 * 					- CodiceAOO, il codice IPA dell'AOO 
 * 					- CodiceRegistro, il codice del Registro  
 * 					- NumeroRegistrazione, il progressivo di protocollo 
 * 					- DataRegistrazione, la data di registrazione 
 * 					- OraRegistrazione, in maniera opzionale l'ora di registrazione
 * 			
 * 
 * <p>Java class for IdentificatoreType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IdentificatoreType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CodiceAmministrazione" type="{http://www.agid.gov.it/protocollo/}CodiceIPA"/&gt;
 *         &lt;element name="CodiceAOO" type="{http://www.agid.gov.it/protocollo/}CodiceIPA"/&gt;
 *         &lt;element name="CodiceRegistro" type="{http://www.agid.gov.it/protocollo/}CodiceRegistroType"/&gt;
 *         &lt;element name="NumeroRegistrazione" type="{http://www.agid.gov.it/protocollo/}NumeroRegistrazioneType"/&gt;
 *         &lt;element name="DataRegistrazione" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="OraRegistrazione" type="{http://www.w3.org/2001/XMLSchema}time" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IdentificatoreType", propOrder = {
    "codiceAmministrazione",
    "codiceAOO",
    "codiceRegistro",
    "numeroRegistrazione",
    "dataRegistrazione",
    "oraRegistrazione"
})
public class IdentificatoreType {

    @XmlElement(name = "CodiceAmministrazione", required = true)
    protected CodiceIPA codiceAmministrazione;
    @XmlElement(name = "CodiceAOO", required = true)
    protected CodiceIPA codiceAOO;
    @XmlElement(name = "CodiceRegistro", required = true)
    protected String codiceRegistro;
    @XmlElement(name = "NumeroRegistrazione", required = true)
    protected String numeroRegistrazione;
    @XmlElement(name = "DataRegistrazione", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dataRegistrazione;
    @XmlElement(name = "OraRegistrazione")
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar oraRegistrazione;

    /**
     * Gets the value of the codiceAmministrazione property.
     * 
     * @return
     *     possible object is
     *     {@link CodiceIPA }
     *     
     */
    public CodiceIPA getCodiceAmministrazione() {
        return codiceAmministrazione;
    }

    /**
     * Sets the value of the codiceAmministrazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodiceIPA }
     *     
     */
    public void setCodiceAmministrazione(CodiceIPA value) {
        this.codiceAmministrazione = value;
    }

    /**
     * Gets the value of the codiceAOO property.
     * 
     * @return
     *     possible object is
     *     {@link CodiceIPA }
     *     
     */
    public CodiceIPA getCodiceAOO() {
        return codiceAOO;
    }

    /**
     * Sets the value of the codiceAOO property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodiceIPA }
     *     
     */
    public void setCodiceAOO(CodiceIPA value) {
        this.codiceAOO = value;
    }

    /**
     * Gets the value of the codiceRegistro property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodiceRegistro() {
        return codiceRegistro;
    }

    /**
     * Sets the value of the codiceRegistro property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodiceRegistro(String value) {
        this.codiceRegistro = value;
    }

    /**
     * Gets the value of the numeroRegistrazione property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroRegistrazione() {
        return numeroRegistrazione;
    }

    /**
     * Sets the value of the numeroRegistrazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroRegistrazione(String value) {
        this.numeroRegistrazione = value;
    }

    /**
     * Gets the value of the dataRegistrazione property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDataRegistrazione() {
        return dataRegistrazione;
    }

    /**
     * Sets the value of the dataRegistrazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataRegistrazione(XMLGregorianCalendar value) {
        this.dataRegistrazione = value;
    }

    /**
     * Gets the value of the oraRegistrazione property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOraRegistrazione() {
        return oraRegistrazione;
    }

    /**
     * Sets the value of the oraRegistrazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOraRegistrazione(XMLGregorianCalendar value) {
        this.oraRegistrazione = value;
    }

}
