//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.08 at 07:27:40 PM CEST 
//


package it.gov.agid.protocollo;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.XmlValue;


/**
 * 
 * 				L'indirizzo contiene i dati relativi ad un'indirizzo.
 * 				
 * 				L'indirizzo è caratterizzato da:
 * 				- Toponimo, il riferimento al nome proprio del luogo 
 * 				- Civico, il riferimento assegnato allo specifico immobile 
 * 				- CAP, il codice di avviamento postale 
 * 				- Comune, il riferimento al Comune
 * 				- Provincia, la provincia 
 * 				- Nazione, la denominazione della nazione e il codice ISO 3166-1 alpha-3
 * 			
 * 
 * <p>Java class for IndirizzoPostaleType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IndirizzoPostaleType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Toponimo" type="{http://www.agid.gov.it/protocollo/}ToponimoType"/&gt;
 *         &lt;element name="Civico" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="CAP" type="{http://www.agid.gov.it/protocollo/}CAPType"/&gt;
 *         &lt;element name="Comune" type="{http://www.agid.gov.it/protocollo/}ComuneType"/&gt;
 *         &lt;element name="Nazione"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                 &lt;attribute name="codice3166" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" default="ITA" /&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IndirizzoPostaleType", propOrder = {
    "toponimo",
    "civico",
    "cap",
    "comune",
    "nazione"
})
public class IndirizzoPostaleType {

    @XmlElement(name = "Toponimo", required = true)
    protected ToponimoType toponimo;
    @XmlElement(name = "Civico", required = true)
    protected String civico;
    @XmlElement(name = "CAP", required = true)
    protected String cap;
    @XmlElement(name = "Comune", required = true)
    protected ComuneType comune;
    @XmlElement(name = "Nazione", required = true, defaultValue = "Italia")
    protected IndirizzoPostaleType.Nazione nazione;

    /**
     * Gets the value of the toponimo property.
     * 
     * @return
     *     possible object is
     *     {@link ToponimoType }
     *     
     */
    public ToponimoType getToponimo() {
        return toponimo;
    }

    /**
     * Sets the value of the toponimo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToponimoType }
     *     
     */
    public void setToponimo(ToponimoType value) {
        this.toponimo = value;
    }

    /**
     * Gets the value of the civico property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCivico() {
        return civico;
    }

    /**
     * Sets the value of the civico property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCivico(String value) {
        this.civico = value;
    }

    /**
     * Gets the value of the cap property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCAP() {
        return cap;
    }

    /**
     * Sets the value of the cap property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCAP(String value) {
        this.cap = value;
    }

    /**
     * Gets the value of the comune property.
     * 
     * @return
     *     possible object is
     *     {@link ComuneType }
     *     
     */
    public ComuneType getComune() {
        return comune;
    }

    /**
     * Sets the value of the comune property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComuneType }
     *     
     */
    public void setComune(ComuneType value) {
        this.comune = value;
    }

    /**
     * Gets the value of the nazione property.
     * 
     * @return
     *     possible object is
     *     {@link IndirizzoPostaleType.Nazione }
     *     
     */
    public IndirizzoPostaleType.Nazione getNazione() {
        return nazione;
    }

    /**
     * Sets the value of the nazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndirizzoPostaleType.Nazione }
     *     
     */
    public void setNazione(IndirizzoPostaleType.Nazione value) {
        this.nazione = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;simpleContent&gt;
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *       &lt;attribute name="codice3166" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" default="ITA" /&gt;
     *     &lt;/extension&gt;
     *   &lt;/simpleContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Nazione {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "codice3166", namespace = "http://www.agid.gov.it/protocollo/")
        @XmlSchemaType(name = "anySimpleType")
        protected String codice3166;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the codice3166 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCodice3166() {
            if (codice3166 == null) {
                return "ITA";
            } else {
                return codice3166;
            }
        }

        /**
         * Sets the value of the codice3166 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCodice3166(String value) {
            this.codice3166 = value;
        }

    }

}
