//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.08 at 07:27:40 PM CEST 
//


package it.gov.agid.protocollo;

import javax.xml.namespace.QName;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.gov.agid.protocollo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SegnaturaInformatica_QNAME = new QName("http://www.agid.gov.it/protocollo/", "SegnaturaInformatica");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.gov.agid.protocollo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link IndirizzoPostaleType }
     * 
     */
    public IndirizzoPostaleType createIndirizzoPostaleType() {
        return new IndirizzoPostaleType();
    }

    /**
     * Create an instance of {@link LivelloType }
     * 
     */
    public LivelloType createLivelloType() {
        return new LivelloType();
    }

    /**
     * Create an instance of {@link SegnaturaInformaticaType }
     * 
     */
    public SegnaturaInformaticaType createSegnaturaInformaticaType() {
        return new SegnaturaInformaticaType();
    }

    /**
     * Create an instance of {@link IntestazioneType }
     * 
     */
    public IntestazioneType createIntestazioneType() {
        return new IntestazioneType();
    }

    /**
     * Create an instance of {@link RiferimentiType }
     * 
     */
    public RiferimentiType createRiferimentiType() {
        return new RiferimentiType();
    }

    /**
     * Create an instance of {@link IdentificatoreType }
     * 
     */
    public IdentificatoreType createIdentificatoreType() {
        return new IdentificatoreType();
    }

    /**
     * Create an instance of {@link CodiceIPA }
     * 
     */
    public CodiceIPA createCodiceIPA() {
        return new CodiceIPA();
    }

    /**
     * Create an instance of {@link FascicoloType }
     * 
     */
    public FascicoloType createFascicoloType() {
        return new FascicoloType();
    }

    /**
     * Create an instance of {@link ClassificaType }
     * 
     */
    public ClassificaType createClassificaType() {
        return new ClassificaType();
    }

    /**
     * Create an instance of {@link RiservatoType }
     * 
     */
    public RiservatoType createRiservatoType() {
        return new RiservatoType();
    }

    /**
     * Create an instance of {@link DescrizioneType }
     * 
     */
    public DescrizioneType createDescrizioneType() {
        return new DescrizioneType();
    }

    /**
     * Create an instance of {@link DestinatarioType }
     * 
     */
    public DestinatarioType createDestinatarioType() {
        return new DestinatarioType();
    }

    /**
     * Create an instance of {@link DocumentoType }
     * 
     */
    public DocumentoType createDocumentoType() {
        return new DocumentoType();
    }

    /**
     * Create an instance of {@link SignType }
     * 
     */
    public SignType createSignType() {
        return new SignType();
    }

    /**
     * Create an instance of {@link DetachedType }
     * 
     */
    public DetachedType createDetachedType() {
        return new DetachedType();
    }

    /**
     * Create an instance of {@link CollocazioneTelematicaType }
     * 
     */
    public CollocazioneTelematicaType createCollocazioneTelematicaType() {
        return new CollocazioneTelematicaType();
    }

    /**
     * Create an instance of {@link SoggettoType }
     * 
     */
    public SoggettoType createSoggettoType() {
        return new SoggettoType();
    }

    /**
     * Create an instance of {@link AmministrazioneType }
     * 
     */
    public AmministrazioneType createAmministrazioneType() {
        return new AmministrazioneType();
    }

    /**
     * Create an instance of {@link AmministrazioneEsteraType }
     * 
     */
    public AmministrazioneEsteraType createAmministrazioneEsteraType() {
        return new AmministrazioneEsteraType();
    }

    /**
     * Create an instance of {@link PersonaGiuridicaType }
     * 
     */
    public PersonaGiuridicaType createPersonaGiuridicaType() {
        return new PersonaGiuridicaType();
    }

    /**
     * Create an instance of {@link ToponimoType }
     * 
     */
    public ToponimoType createToponimoType() {
        return new ToponimoType();
    }

    /**
     * Create an instance of {@link ComuneType }
     * 
     */
    public ComuneType createComuneType() {
        return new ComuneType();
    }

    /**
     * Create an instance of {@link ImprontaType }
     * 
     */
    public ImprontaType createImprontaType() {
        return new ImprontaType();
    }

    /**
     * Create an instance of {@link PersonaFisicaType }
     * 
     */
    public PersonaFisicaType createPersonaFisicaType() {
        return new PersonaFisicaType();
    }

    /**
     * Create an instance of {@link ContattiType }
     * 
     */
    public ContattiType createContattiType() {
        return new ContattiType();
    }

    /**
     * Create an instance of {@link IndirizzoTelematicoType }
     * 
     */
    public IndirizzoTelematicoType createIndirizzoTelematicoType() {
        return new IndirizzoTelematicoType();
    }

    /**
     * Create an instance of {@link IndirizzoPostaleType.Nazione }
     * 
     */
    public IndirizzoPostaleType.Nazione createIndirizzoPostaleTypeNazione() {
        return new IndirizzoPostaleType.Nazione();
    }

    /**
     * Create an instance of {@link LivelloType.Livello }
     * 
     */
    public LivelloType.Livello createLivelloTypeLivello() {
        return new LivelloType.Livello();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SegnaturaInformaticaType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SegnaturaInformaticaType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.agid.gov.it/protocollo/", name = "SegnaturaInformatica")
    public JAXBElement<SegnaturaInformaticaType> createSegnaturaInformatica(SegnaturaInformaticaType value) {
        return new JAXBElement<SegnaturaInformaticaType>(_SegnaturaInformatica_QNAME, SegnaturaInformaticaType.class, null, value);
    }

}
