//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.08 at 07:27:40 PM CEST 
//


package it.gov.agid.protocollo;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PersonaGiuridicaType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PersonaGiuridicaType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Denominazione" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="PIVAoCF" type="{http://www.agid.gov.it/protocollo/}PartitaIVA" minOccurs="0"/&gt;
 *         &lt;element name="ContattiPersonaGiuridica" type="{http://www.agid.gov.it/protocollo/}ContattiType" minOccurs="0"/&gt;
 *         &lt;element name="PersonaFisica" type="{http://www.agid.gov.it/protocollo/}PersonaFisicaType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PersonaGiuridicaType", propOrder = {
    "denominazione",
    "pivAoCF",
    "contattiPersonaGiuridica",
    "personaFisica"
})
public class PersonaGiuridicaType {

    @XmlElement(name = "Denominazione", required = true)
    protected String denominazione;
    @XmlElement(name = "PIVAoCF")
    protected String pivAoCF;
    @XmlElement(name = "ContattiPersonaGiuridica")
    protected ContattiType contattiPersonaGiuridica;
    @XmlElement(name = "PersonaFisica")
    protected List<PersonaFisicaType> personaFisica;

    /**
     * Gets the value of the denominazione property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDenominazione() {
        return denominazione;
    }

    /**
     * Sets the value of the denominazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDenominazione(String value) {
        this.denominazione = value;
    }

    /**
     * Gets the value of the pivAoCF property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPIVAoCF() {
        return pivAoCF;
    }

    /**
     * Sets the value of the pivAoCF property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPIVAoCF(String value) {
        this.pivAoCF = value;
    }

    /**
     * Gets the value of the contattiPersonaGiuridica property.
     * 
     * @return
     *     possible object is
     *     {@link ContattiType }
     *     
     */
    public ContattiType getContattiPersonaGiuridica() {
        return contattiPersonaGiuridica;
    }

    /**
     * Sets the value of the contattiPersonaGiuridica property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContattiType }
     *     
     */
    public void setContattiPersonaGiuridica(ContattiType value) {
        this.contattiPersonaGiuridica = value;
    }

    /**
     * Gets the value of the personaFisica property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the personaFisica property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPersonaFisica().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PersonaFisicaType }
     * 
     * 
     */
    public List<PersonaFisicaType> getPersonaFisica() {
        if (personaFisica == null) {
            personaFisica = new ArrayList<PersonaFisicaType>();
        }
        return this.personaFisica;
    }

}
