//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.08 at 07:27:40 PM CEST 
//


package it.gov.agid.protocollo;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 * 				Dati per permettere al mittente di indicare il messaggio di protocollo ricevuto che ha determinato la presente segnatura
 * 				
 * 				- Identificatore, i dati per identificare univocamente il messaggio di protocollo in attuazione all'art. 55 del DPR 445/2000
 * 				- PrimaRegistrazione, si riferisce all'Identificatore di registrazione primario, cioè attribuito per la prima volta ad un documento protocollato che viene ritrasmesso più volte. Deve essere specificato solo se non coincide con l'Identificatore del messaggio protocollato.
 * 				- Oggetto, sintesi dei contenuti di carattere giuridico, amministrativo e narrativo di un documento 
 * 				- Classifica, la categoria del Titolario di classificazione associato al messaggio di protocollo
 * 				- Fascicolo, opzionalmente, il fascicolo entro cui è presente il messaggio di protocollo
 * 			
 * 
 * <p>Java class for RiferimentiType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RiferimentiType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Identificatore" type="{http://www.agid.gov.it/protocollo/}IdentificatoreType"/&gt;
 *         &lt;element name="PrimaRegistrazione" type="{http://www.agid.gov.it/protocollo/}IdentificatoreType" minOccurs="0"/&gt;
 *         &lt;element name="Oggetto" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Classifica" type="{http://www.agid.gov.it/protocollo/}ClassificaType"/&gt;
 *         &lt;element name="Fascicolo" type="{http://www.agid.gov.it/protocollo/}FascicoloType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RiferimentiType", propOrder = {
    "identificatore",
    "primaRegistrazione",
    "oggetto",
    "classifica",
    "fascicolo"
})
public class RiferimentiType {

    @XmlElement(name = "Identificatore", required = true)
    protected IdentificatoreType identificatore;
    @XmlElement(name = "PrimaRegistrazione")
    protected IdentificatoreType primaRegistrazione;
    @XmlElement(name = "Oggetto", required = true)
    protected String oggetto;
    @XmlElement(name = "Classifica", required = true)
    protected ClassificaType classifica;
    @XmlElement(name = "Fascicolo")
    protected FascicoloType fascicolo;

    /**
     * Gets the value of the identificatore property.
     * 
     * @return
     *     possible object is
     *     {@link IdentificatoreType }
     *     
     */
    public IdentificatoreType getIdentificatore() {
        return identificatore;
    }

    /**
     * Sets the value of the identificatore property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentificatoreType }
     *     
     */
    public void setIdentificatore(IdentificatoreType value) {
        this.identificatore = value;
    }

    /**
     * Gets the value of the primaRegistrazione property.
     * 
     * @return
     *     possible object is
     *     {@link IdentificatoreType }
     *     
     */
    public IdentificatoreType getPrimaRegistrazione() {
        return primaRegistrazione;
    }

    /**
     * Sets the value of the primaRegistrazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentificatoreType }
     *     
     */
    public void setPrimaRegistrazione(IdentificatoreType value) {
        this.primaRegistrazione = value;
    }

    /**
     * Gets the value of the oggetto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOggetto() {
        return oggetto;
    }

    /**
     * Sets the value of the oggetto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOggetto(String value) {
        this.oggetto = value;
    }

    /**
     * Gets the value of the classifica property.
     * 
     * @return
     *     possible object is
     *     {@link ClassificaType }
     *     
     */
    public ClassificaType getClassifica() {
        return classifica;
    }

    /**
     * Sets the value of the classifica property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClassificaType }
     *     
     */
    public void setClassifica(ClassificaType value) {
        this.classifica = value;
    }

    /**
     * Gets the value of the fascicolo property.
     * 
     * @return
     *     possible object is
     *     {@link FascicoloType }
     *     
     */
    public FascicoloType getFascicolo() {
        return fascicolo;
    }

    /**
     * Sets the value of the fascicolo property.
     * 
     * @param value
     *     allowed object is
     *     {@link FascicoloType }
     *     
     */
    public void setFascicolo(FascicoloType value) {
        this.fascicolo = value;
    }

}
