//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.08 at 07:27:40 PM CEST 
//


package it.gov.agid.protocollo;

import jakarta.xml.bind.annotation.*;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.w3._2000._09.xmldsig_.SignatureType;


/**
 * 
 * 				La segnatura di protocollo contine i dati relativi ad un messaggio di protocollo.
 * 				
 * 				Un messaggio di protocollo è determinato da:
 * 					- documento primario
 * 					- eventuali allegati
 * 					- la segnatura di protocollo qui definita
 * 					
 * 				La segnatura di protocollo è associata in forma permanente al documento primario e agli allegati che con esso formano il messaggio di protocollo
 * 				includendo nella segnatatura di protocollo le impronte (digest) del documento primario e degli allegati e assicurando l’autenticità e integrità
 * 				della segnatura di protocollo firmando la stessa implementando il profilo XAdES baseline B level signatures definito in ETSI EN 319 132-1 v1.1.1.
 * 
 * 				La segnatura di protocollo è caratterizzata da:
 * 				- Intestazione, i dati necessari per idividuare univocamente il messaggio di protocollo
 * 				- Riferimento, opzionalmente, dati per permettere al mittente di indicare il messaggio di protocollo ricevuto che ha determinato la presente segnatura
 * 				- Descrizione, i dati aggiuntivi del messaggio di protocollo
 * 				- Signature, i dati e metadati della firma dell'XML (profilo XAdES baseline B level signatures definito in ETSI EN 319 132-1 v1.1.1) 
 * 			
 * 
 * <p>Java class for SegnaturaInformaticaType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SegnaturaInformaticaType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Intestazione" type="{http://www.agid.gov.it/protocollo/}IntestazioneType"/&gt;
 *         &lt;element name="Riferimenti" type="{http://www.agid.gov.it/protocollo/}RiferimentiType" minOccurs="0"/&gt;
 *         &lt;element name="Descrizione" type="{http://www.agid.gov.it/protocollo/}DescrizioneType"/&gt;
 *         &lt;element ref="{http://www.w3.org/2000/09/xmldsig#}Signature"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="versione" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" fixed="3.0.0" /&gt;
 *       &lt;attribute name="lang" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" fixed="it" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SegnaturaInformaticaType", propOrder = {
    "intestazione",
    "riferimenti",
    "descrizione",
    "signature"
})
public class SegnaturaInformaticaType {

    @XmlElement(name = "Intestazione", required = true)
    protected IntestazioneType intestazione;
    @XmlElement(name = "Riferimenti")
    protected RiferimentiType riferimenti;
    @XmlElement(name = "Descrizione", required = true)
    protected DescrizioneType descrizione;
    @XmlElement(name = "Signature", namespace = "http://www.w3.org/2000/09/xmldsig#", required = true)
    protected SignatureType signature;
    @XmlAttribute(name = "versione", namespace = "http://www.agid.gov.it/protocollo/", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String versione;
    @XmlAttribute(name = "lang", namespace = "http://www.agid.gov.it/protocollo/", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String lang;

    /**
     * Gets the value of the intestazione property.
     * 
     * @return
     *     possible object is
     *     {@link IntestazioneType }
     *     
     */
    public IntestazioneType getIntestazione() {
        return intestazione;
    }

    /**
     * Sets the value of the intestazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntestazioneType }
     *     
     */
    public void setIntestazione(IntestazioneType value) {
        this.intestazione = value;
    }

    /**
     * Gets the value of the riferimenti property.
     * 
     * @return
     *     possible object is
     *     {@link RiferimentiType }
     *     
     */
    public RiferimentiType getRiferimenti() {
        return riferimenti;
    }

    /**
     * Sets the value of the riferimenti property.
     * 
     * @param value
     *     allowed object is
     *     {@link RiferimentiType }
     *     
     */
    public void setRiferimenti(RiferimentiType value) {
        this.riferimenti = value;
    }

    /**
     * Gets the value of the descrizione property.
     * 
     * @return
     *     possible object is
     *     {@link DescrizioneType }
     *     
     */
    public DescrizioneType getDescrizione() {
        return descrizione;
    }

    /**
     * Sets the value of the descrizione property.
     * 
     * @param value
     *     allowed object is
     *     {@link DescrizioneType }
     *     
     */
    public void setDescrizione(DescrizioneType value) {
        this.descrizione = value;
    }

    /**
     * Gets the value of the signature property.
     * 
     * @return
     *     possible object is
     *     {@link SignatureType }
     *     
     */
    public SignatureType getSignature() {
        return signature;
    }

    /**
     * Sets the value of the signature property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignatureType }
     *     
     */
    public void setSignature(SignatureType value) {
        this.signature = value;
    }

    /**
     * Gets the value of the versione property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersione() {
        if (versione == null) {
            return "3.0.0";
        } else {
            return versione;
        }
    }

    /**
     * Sets the value of the versione property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersione(String value) {
        this.versione = value;
    }

    /**
     * Gets the value of the lang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLang() {
        if (lang == null) {
            return "it";
        } else {
            return lang;
        }
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLang(String value) {
        this.lang = value;
    }

}
