//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.08 at 07:27:40 PM CEST 
//


package it.gov.agid.protocollo;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SignType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SignType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="UnDetached" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="Detached" type="{http://www.agid.gov.it/protocollo/}DetachedType" maxOccurs="unbounded"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SignType", propOrder = {
    "unDetached",
    "detached"
})
public class SignType {

    @XmlElement(name = "UnDetached")
    protected Boolean unDetached;
    @XmlElement(name = "Detached")
    protected List<DetachedType> detached;

    /**
     * Gets the value of the unDetached property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUnDetached() {
        return unDetached;
    }

    /**
     * Sets the value of the unDetached property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUnDetached(Boolean value) {
        this.unDetached = value;
    }

    /**
     * Gets the value of the detached property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the detached property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDetached().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DetachedType }
     * 
     * 
     */
    public List<DetachedType> getDetached() {
        if (detached == null) {
            detached = new ArrayList<DetachedType>();
        }
        return this.detached;
    }

}
