//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.08 at 07:27:40 PM CEST 
//


package it.gov.agid.protocollo;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 * 				Il soggetto contiene i dati per referenziare un corrispondente, che può essere:
 * 				- una Amministrazione italiana (Amministrazione e opzionalmente AOO e UO) ed opzionalmente una persona fisica interna dell'amministrazione
 * 				- una persona fisica
 * 				- una persona giuridica ed opzionalmente un riferimento ad persona fisica interna
 * 				- una Amministrazione estera
 * 			
 * 
 * <p>Java class for SoggettoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SoggettoType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="Amministrazione" type="{http://www.agid.gov.it/protocollo/}AmministrazioneType"/&gt;
 *         &lt;element name="PersonaGiuridica" type="{http://www.agid.gov.it/protocollo/}PersonaGiuridicaType"/&gt;
 *         &lt;element name="PersonaFisica" type="{http://www.agid.gov.it/protocollo/}PersonaFisicaType"/&gt;
 *         &lt;element name="AmministrazioneEstera" type="{http://www.agid.gov.it/protocollo/}AmministrazioneEsteraType"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SoggettoType", propOrder = {
    "amministrazione",
    "personaGiuridica",
    "personaFisica",
    "amministrazioneEstera"
})
@XmlSeeAlso({
    DestinatarioType.class
})
public class SoggettoType {

    @XmlElement(name = "Amministrazione")
    protected AmministrazioneType amministrazione;
    @XmlElement(name = "PersonaGiuridica")
    protected PersonaGiuridicaType personaGiuridica;
    @XmlElement(name = "PersonaFisica")
    protected PersonaFisicaType personaFisica;
    @XmlElement(name = "AmministrazioneEstera")
    protected AmministrazioneEsteraType amministrazioneEstera;

    /**
     * Gets the value of the amministrazione property.
     * 
     * @return
     *     possible object is
     *     {@link AmministrazioneType }
     *     
     */
    public AmministrazioneType getAmministrazione() {
        return amministrazione;
    }

    /**
     * Sets the value of the amministrazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmministrazioneType }
     *     
     */
    public void setAmministrazione(AmministrazioneType value) {
        this.amministrazione = value;
    }

    /**
     * Gets the value of the personaGiuridica property.
     * 
     * @return
     *     possible object is
     *     {@link PersonaGiuridicaType }
     *     
     */
    public PersonaGiuridicaType getPersonaGiuridica() {
        return personaGiuridica;
    }

    /**
     * Sets the value of the personaGiuridica property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonaGiuridicaType }
     *     
     */
    public void setPersonaGiuridica(PersonaGiuridicaType value) {
        this.personaGiuridica = value;
    }

    /**
     * Gets the value of the personaFisica property.
     * 
     * @return
     *     possible object is
     *     {@link PersonaFisicaType }
     *     
     */
    public PersonaFisicaType getPersonaFisica() {
        return personaFisica;
    }

    /**
     * Sets the value of the personaFisica property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonaFisicaType }
     *     
     */
    public void setPersonaFisica(PersonaFisicaType value) {
        this.personaFisica = value;
    }

    /**
     * Gets the value of the amministrazioneEstera property.
     * 
     * @return
     *     possible object is
     *     {@link AmministrazioneEsteraType }
     *     
     */
    public AmministrazioneEsteraType getAmministrazioneEstera() {
        return amministrazioneEstera;
    }

    /**
     * Sets the value of the amministrazioneEstera property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmministrazioneEsteraType }
     *     
     */
    public void setAmministrazioneEstera(AmministrazioneEsteraType value) {
        this.amministrazioneEstera = value;
    }

}
