//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.08 at 07:27:40 PM CEST 
//


package it.gov.agid.protocollo;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 * 				Il toponimo contiene il riferimento al nome proprio del luogo
 * 				
 * 				Il toponimo è carattirizzato da:
 * 				- dug, denominazione urbanistica generica o qualitficatore del toponimo (e.g., via, viale, piazza, ecc.)
 * 				- duf, denominazione urbanistica ufficiale o nome della strada
 * 			
 * 
 * <p>Java class for ToponimoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ToponimoType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="dug" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="duf" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ToponimoType", propOrder = {
    "dug",
    "duf"
})
public class ToponimoType {

    @XmlElement(required = true)
    protected String dug;
    @XmlElement(required = true)
    protected String duf;

    /**
     * Gets the value of the dug property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDug() {
        return dug;
    }

    /**
     * Sets the value of the dug property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDug(String value) {
        this.dug = value;
    }

    /**
     * Gets the value of the duf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDuf() {
        return duf;
    }

    /**
     * Sets the value of the duf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDuf(String value) {
        this.duf = value;
    }

}
