INSERT INTO struttura_fascicolo_dipendente (id, nome, id_padre, tipologia, is_leaf) VALUES
(1, 'Adempimenti Fiscali, Contributivi, Previdenziali, Assistenziali, Assicurativi', null, 'FascicoloLv2', true),
(2, 'Assegnazioni, distacchi, prese di servizio, trasferimenti', null, 'FascicoloLv2', true),
(3, 'Assunzione', null, 'FascicoloLv2', true),
(4, 'Cambio di profilo', null, 'FascicoloLv2', true),
(5, 'Certificati Medici', null, 'FascicoloLv2', true),
(6, 'Comandi e mobilità', null, 'FascicoloLv2', false),
(7, 'Comunicazioni obbligatorie', null, 'FascicoloLv2', true),
(8, 'Formazione, Aggiornamento', null, 'FascicoloLv2', false),
(9, 'Infortuni ', null, 'FascicoloLv2', true),
(10, 'Lavoro Agile', null, 'FascicoloLv2', true),
(11, 'Maternità', null, 'FascicoloLv2', true),
(12, 'Permessi studio', null, 'FascicoloLv2', true),
(13, 'Perseo', null, 'FascicoloLv2', true),
(14, 'Procedimenti Disciplinari', null, 'FascicoloLv2', true),
(15, 'Quiescenza e Previdenza', null, 'FascicoloLv2', false),
(16, 'Richieste visite fiscali e referti ', null, 'FascicoloLv2', true),
(17, 'Ritenute', null, 'FascicoloLv2', true),
(18, 'Schede di valutazione ed incarichi', null, 'FascicoloLv2', true),
(19, 'Sorveglianza sanitaria obbligatoria', null, 'FascicoloLv2', true),
(20, 'Titoli di studio', null, 'FascicoloLv2', true),
(21, 'Trattamento Economico', null, 'FascicoloLv2', true),
(22, 'Trattamento Giuridico', null, 'FascicoloLv2', false),
(23, 'Voci stipendiali', null, 'FascicoloLv2', true),
(24, 'Entrata Mobilità', 6, 'FascicoloLv3', true),
(25, 'Uscita Mobilità', 6, 'FascicoloLv3', true),
(26, 'Entrata Comandi', 6, 'FascicoloLv3', true),
(27, 'Uscita Comandi', 6, 'FascicoloLv3', true),
(28, 'Interna', 8, 'FascicoloLv3', true),
(29, 'Esterna', 8, 'FascicoloLv3', true),
(30, 'Pensione', 15, 'FascicoloLv3', true),
(31, 'TFS/TFR', 15, 'FascicoloLv3', true),
(32, 'Riscatti e ricongiunzioni', 15, 'FascicoloLv3', true),
(33, 'Sistemazione', 15, 'FascicoloLv3', true),
(34, 'Anagrafe  Prestazioni', 22, 'FascicoloLv3', true),
(35, 'Azioni di rivalsa', 22, 'FascicoloLv3', true),
(36, 'Cause di servizio', 22, 'FascicoloLv3', true),
(37, 'Contenzioso', 22, 'FascicoloLv3', true),
(38, 'Gestione rilevazioni presenze', 22, 'FascicoloLv3', true),
(39, 'Legge 104/92', 22, 'FascicoloLv3', true),
(40, 'Patrocinio Legale', 22, 'FascicoloLv3', true),
(41, 'Servizio ispettivo', 22, 'FascicoloLv3', true),
(42, 'Visite medico collegiali', 22, 'FascicoloLv3', true),
(43, 'Part-time', 22, 'FascicoloLv3', true),
(44, 'Permessi, Congedi, Aspettative', 22, 'FascicoloLv3', true);